### ISSUE TITLE
[레이아웃] 레이아웃 페이지 개발

### ISSUE THREAD

**Issue by sooojungee** [woowa-techcamp-2020/todo-5#1]
**헤더 html 작성**

**메뉴 버튼 애니메이션**
- [x] 메뉴 레이어 왼쪽 방향으로 슬라이드 애니메이션
- [x] x버튼 클릭 시 오른쪽 방향으로 슬라이드 애니메이션

**Activity 리스트 폼 개발**
- [x] 사용자명
- [x] 액션 종류 (add, remove, update, move)
- [x] element Title
- [x] Form 탭, To 탭
- [x] 변경시간

**Comment by Loloara** [comment]
개발 완료했습니다.
