### ISSUE TITLE
[Boilerplate] Frontend Boilerplate

### ISSUE THREAD

**Issue by Loloara** [woowa-techcamp-2020/todo-5#8]
- [x] 디렉토리 구조 만들기
- [x] 바벨 컨피그
- [x] ts config (backend 와 동일)
- [x] sourceMap 설정
- [x] 레이아웃 폼 구성 (index, header, content, footer)
- [x] 컴포넌트 설정 (modal)

**Comment by sooojungee** [comment]
완성
